Traceback (most recent call last):
  File "/usr/share/miniconda/envs/pylipd/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/share/miniconda/envs/pylipd/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda/envs/pylipd/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/share/miniconda/envs/pylipd/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/share/miniconda/envs/pylipd/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda/envs/pylipd/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda/envs/pylipd/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
path = '../data/MyWonderfulRecord.LinkedEarth.2024.lpd'
D = LiPD()
D.load(path)
------------------

----- stdout -----
Loading 1 LiPD files
----- stderr -----
  0%|          | 0/1 [00:00<?, ?it/s]
----- stderr -----
  0%|          | 0/1 [00:00<?, ?it/s]
----- stdout -----
ERROR: Could not convert LiPD file ../data/MyWonderfulRecord.LinkedEarth.2024.lpd to RDF
----- stderr -----

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[3], line 3[0m
[1;32m      1[0m path [38;5;241m=[39m [38;5;124m'[39m[38;5;124m../data/MyWonderfulRecord.LinkedEarth.2024.lpd[39m[38;5;124m'[39m
[1;32m      2[0m D [38;5;241m=[39m LiPD()
[0;32m----> 3[0m [43mD[49m[38;5;241;43m.[39;49m[43mload[49m[43m([49m[43mpath[49m[43m)[49m

File [0;32m/usr/share/miniconda/envs/pylipd/lib/python3.10/site-packages/pylipd/lipd.py:145[0m, in [0;36mLiPD.load[0;34m(self, lipdfiles, parallel, standardize, add_labels)[0m
[1;32m    143[0m numfiles [38;5;241m=[39m [38;5;28mlen[39m(lipdfiles)
[1;32m    144[0m [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mLoading [39m[38;5;132;01m{[39;00mnumfiles[38;5;132;01m}[39;00m[38;5;124m LiPD files[39m[38;5;124m"[39m)
[0;32m--> 145[0m [38;5;28mself[39m[38;5;241m.[39mgraph [38;5;241m=[39m [43mmulti_load_lipd[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mgraph[49m[43m,[49m[43m [49m[43mlipdfiles[49m[43m,[49m[43m [49m[43mparallel[49m[43m,[49m[43m [49m[43mstandardize[49m[43m,[49m[43m [49m[43madd_labels[49m[43m)[49m
[1;32m    146[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mLoaded..[39m[38;5;124m"[39m)

File [0;32m/usr/share/miniconda/envs/pylipd/lib/python3.10/site-packages/pylipd/utils/multi_processing.py:57[0m, in [0;36mmulti_load_lipd[0;34m(graph, lipdfiles, parallel, standardize, add_labels)[0m
[1;32m     55[0m [38;5;28;01mfor[39;00m i [38;5;129;01min[39;00m tqdm([38;5;28mrange[39m([38;5;241m0[39m, [38;5;28mlen[39m(args))):
[1;32m     56[0m     arg [38;5;241m=[39m args[i]
[0;32m---> 57[0m     subgraph [38;5;241m=[39m [43mconvert_lipd_to_graph[49m[43m([49m[43marg[49m[43m)[49m
[1;32m     58[0m     graph[38;5;241m.[39maddN(subgraph[38;5;241m.[39mquads())
[1;32m     59[0m     [38;5;28;01mdel[39;00m subgraph

File [0;32m/usr/share/miniconda/envs/pylipd/lib/python3.10/site-packages/pylipd/utils/multi_processing.py:40[0m, in [0;36mconvert_lipd_to_graph[0;34m(arg)[0m
[1;32m     38[0m [38;5;28;01mexcept[39;00m [38;5;167;01mException[39;00m [38;5;28;01mas[39;00m e:
[1;32m     39[0m     [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mERROR: Could not convert LiPD file [39m[38;5;132;01m{[39;00mlipdfile[38;5;132;01m}[39;00m[38;5;124m to RDF[39m[38;5;124m"[39m)            
[0;32m---> 40[0m     [38;5;28;01mraise[39;00m e

File [0;32m/usr/share/miniconda/envs/pylipd/lib/python3.10/site-packages/pylipd/utils/multi_processing.py:36[0m, in [0;36mconvert_lipd_to_graph[0;34m(arg)[0m
[1;32m     34[0m [38;5;28;01mtry[39;00m:
[1;32m     35[0m     converter [38;5;241m=[39m LipdToRDF(standardize, add_labels)
[0;32m---> 36[0m     [43mconverter[49m[38;5;241;43m.[39;49m[43mconvert[49m[43m([49m[43mlipdfile[49m[43m)[49m
[1;32m     37[0m     [38;5;28;01mreturn[39;00m converter[38;5;241m.[39mgraph
[1;32m     38[0m [38;5;28;01mexcept[39;00m [38;5;167;01mException[39;00m [38;5;28;01mas[39;00m e:

File [0;32m/usr/share/miniconda/envs/pylipd/lib/python3.10/site-packages/pylipd/utils/lipd_to_rdf.py:65[0m, in [0;36mLipdToRDF.convert[0;34m(self, lipdpath)[0m
[1;32m     62[0m [38;5;28mself[39m[38;5;241m.[39mgraphurl [38;5;241m=[39m NSURL [38;5;241m+[39m [38;5;124m"[39m[38;5;124m/[39m[38;5;124m"[39m [38;5;241m+[39m lpdname
[1;32m     64[0m [38;5;28;01mwith[39;00m tempfile[38;5;241m.[39mTemporaryDirectory(prefix[38;5;241m=[39m[38;5;124m"[39m[38;5;124mlipd_to_rdf_[39m[38;5;124m"[39m) [38;5;28;01mas[39;00m tmpdir:
[0;32m---> 65[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_unzip_lipd_file[49m[43m([49m[43mlipdpath[49m[43m,[49m[43m [49m[43mtmpdir[49m[43m)[49m
[1;32m     66[0m     jsons [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_find_files_with_extension(tmpdir, [38;5;124m'[39m[38;5;124mjsonld[39m[38;5;124m'[39m)
[1;32m     67[0m     [38;5;28;01mfor[39;00m jsonpath, _ [38;5;129;01min[39;00m jsons:

File [0;32m/usr/share/miniconda/envs/pylipd/lib/python3.10/site-packages/pylipd/utils/lipd_to_rdf.py:129[0m, in [0;36mLipdToRDF._unzip_lipd_file[0;34m(self, lipdfile, unzipdir)[0m
[1;32m    125[0m         zip_ref[38;5;241m.[39mextractall(unzipdir)
[1;32m    126[0m [38;5;28;01melse[39;00m:
[1;32m    127[0m     [38;5;66;03m# If this is a local file[39;00m
[1;32m    128[0m     [38;5;66;03m# Unzip file[39;00m
[0;32m--> 129[0m     [38;5;28;01mwith[39;00m [43mzipfile[49m[38;5;241;43m.[39;49m[43mZipFile[49m[43m([49m[43mlipdfile[49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43mr[39;49m[38;5;124;43m'[39;49m[43m)[49m [38;5;28;01mas[39;00m zip_ref:
[1;32m    130[0m         zip_ref[38;5;241m.[39mextractall(unzipdir)

File [0;32m/usr/share/miniconda/envs/pylipd/lib/python3.10/zipfile.py:1254[0m, in [0;36mZipFile.__init__[0;34m(self, file, mode, compression, allowZip64, compresslevel, strict_timestamps)[0m
[1;32m   1252[0m [38;5;28;01mwhile[39;00m [38;5;28;01mTrue[39;00m:
[1;32m   1253[0m     [38;5;28;01mtry[39;00m:
[0;32m-> 1254[0m         [38;5;28mself[39m[38;5;241m.[39mfp [38;5;241m=[39m [43mio[49m[38;5;241;43m.[39;49m[43mopen[49m[43m([49m[43mfile[49m[43m,[49m[43m [49m[43mfilemode[49m[43m)[49m
[1;32m   1255[0m     [38;5;28;01mexcept[39;00m [38;5;167;01mOSError[39;00m:
[1;32m   1256[0m         [38;5;28;01mif[39;00m filemode [38;5;129;01min[39;00m modeDict:

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '../data/MyWonderfulRecord.LinkedEarth.2024.lpd'

